[build]
    command = "yarn build"

[dev]
    command = "remix vite:dev"
    port = 3000

[[headers]]
    for = "/build/*"
    [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
